
export const VIDEO_GENERATION_MESSAGES = [
    "IGNITING HEAVY GENERATION TURBINES...",
    "CALIBRATING HYDRAULIC FRAME RIGGING...",
    "SURVEYING CINEMATIC TOPOGRAPHY...",
    "ASSEMBLING PIXEL SCAFFOLDING...",
    "POURING DIGITAL CONCRETE LAYERS...",
    "WELDING MOTION KEYFRAMES...",
    "STRUCTURAL RENDERING IN PROGRESS - STANDBY...",
    "APPLYING INDUSTRIAL POST-FABRICATION...",
    "PERFORMING FINAL SITE INSPECTION...",
];
